name: multi-job

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build-demo"

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test-demo"